### PR TITLE
Use eslint and prettier

### PR DESCRIPTION
**Pull request by kennarddh**
#### Description

Use eslint and prettier
#3

### CODE REVIEW

**Review by mcqua007 — CHANGES_REQUESTED** [review]
Can you use yarn as your package manager as that is what this project uses. When you use npm you create a package-lock.json alongside yarn.lock. Or at least not commit it.  

Also in package-json can you use npx for the eslint and prettier commands.

For PRs can you also target the staging branch rather than master (I need to add this in the PR template).

Thank you!

**Comment by kennarddh** [comment]
Add package-lock.json to gitignore?

**Comment by mcqua007** [comment]
@kennarddh Yeah I can do that. Also I'm noticing in your recent some changes I already made, the JsBin link in the issue template and then the version in package.json these are changes are already in staging and master. If you can remove those changes using so they don't cause any merge conflicts that would be great. https://github.com/mcqua007/quantdom/commit/7c67695b46dad312465b02d8822767afa177e221

With each PR I only want changes that were referenced in the PR so the PRs are as concise as possible. For example this PR references prettier and eslint so the committed files should be limited to package.json, yarn.lock, and prettier and eslint config files.

Then make sure to always pull master before you commit so you have the latest changes before committing.

**Comment by kennarddh** [comment]
@mcqua007 How to resolve merge conflict in yarn.lock

Is this how to resolve merge conflict in yarn.lock
[link](https://stackoverflow.com/questions/42939113/how-do-you-resolve-git-conflicts-in-yarn-lock)

Can you add package-lock.json in gitignore

**Comment by mcqua007** [comment]
@kennarddh I think this PR need to be re-done. The way you did your most recent ones where there is ot extra commits and remember to use npx for eslint and prettier commands. Also pull most recent changes before committing and only commit package.json, yarn.lock (by using yarn add to install eslint and prettier) and eslint and prettier config files. The commit history has some weird stuff going on like the docs fix PR which I had to revert do some errors and the same issue.

-------------
**Added eslint and prettier to project**

Added the changes because your PR had some issues with unclean commits and there was errors in your code as well. I really appreciate your help and I think this was a great proposal. Good job on all the testing changes. For future changes you can target master as using staging is too cumbersome and made the commit history a little messy.

Here are the changes for reference:

eslint - https://github.com/mcqua007/quantdom/pull/15 & prettier - b32c2368f5a11a1ee728b7024a640cf05fecc327

**Comment by mcqua007** [comment]
@kennarddh 

> @mcqua007 How to resolve merge conflict in yarn.lock
> 
> Is this how to resolve merge conflict in yarn.lock [link](https://stackoverflow.com/questions/42939113/how-do-you-resolve-git-conflicts-in-yarn-lock)
> 
> Can you add package-lock.json in gitignore

If you are getting merge conflicts usually something is wrong in your Git work flow. Either you aren't getting recent changes before committing or something like that. So its best to trying and re-work those steps by checking out a clean branch and getting the most recent changes than re-adding the changes in order to see if that results in no merge conflict. We don't want yarn.lock getting messed up as that can cause problems for the project. Thats why I recommend re-submitting this PR with clean changes. And always target the staging branch when making your PR. Maybe Ill try adding these changes myself later today in order to make sure yarn.lock doesn't get messed up or the commit history. for some reason in your PRs I am getting a lot of merge conflicts when I don't see a normal reason for them to occur again this points to something in the way you are making branches or merging changes etc...

Your work flow should me pull down origin mater for latest changes from my master into your local master. Then create a new branch make your changes (only commit files you actively changed - no built files). Then publish that branch to your remote origin.  Once that is done you can request a PR to merge you branch into quantdom's staging branch. ie. kennarddh/new-branch ---> staging. Check the commit history should only have your changed commits not merges of code of old changes already merged into my master or anything like that. If thats the case you make need to look at rebasing you branch before creating a PR.

If you look at some of these changes you are pushing up some of them don't actually have any changes, and shouldn't be commited. 99c5e8486cebcc2125d986a8ab14f11d82ee43b7

**Pull request closed without merging**
