### PR TITLE
Fix docs script

### PR DESCRIPTION
**Pull request by kennarddh**
#### Description

Fix docs script
#2

### CODE REVIEW

**Comment by mcqua007** [comment]
This is running it globally we need to run it from node_modules m/.bin are you sure your are running in the root of the project ? 

The other options is to use `npx jsdoc2md`. Though all my projectsat work use ./node_modules/.bin and no one has had an issue. 

I'm fine with adding the output section but I don't want to use a global command so we need to run it from bin by using either `npx jsdoc2md` or `./node_modules/.bin jsdoc2md`

**Comment by kennarddh** [comment]
@mcqua007 I can't use ./node_modules/.bin jsdoc2md

**Comment by mcqua007** [comment]
> @mcqua007 I can't use ./node_modules/.bin jsdoc2md

@kennarddh Try my latest change that uses npx. https://github.com/mcqua007/quantdom/commit/8e803e843bbe9e22fdaefa505bdd916cc04e4d5a We need to use packages installed on the project level.
https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b

**Comment by kennarddh** [comment]
Still can't

Error:
```bash
$ npm run docs

> quantdom@1.1.14 docs
> npx jsdoc2md src/index.js > docs.md

JSDOC_ERROR: There are no input files to process.
```

**Comment by mcqua007** [comment]
> Still can't
> 
> 
> 
> Error:
> 
> ```bash
> 
> $ npm run docs
> 
> 
> 
> > quantdom@1.1.14 docs
> 
> > npx jsdoc2md src/index.js > docs.md
> 
> 
> 
> JSDOC_ERROR: There are no input files to process.
> 
> ```

This is better this is an error from the command. The issue is it probably needs to be ./src/index.js I'll add that now. It's wierd your system won't resolve the path are you on a Windows machine ? Maybe its bash or something either  was I think ./ will fix it.

**Comment by kennarddh** [comment]
Still can't

Error:

```bash
$ npm run docs

> quantdom@1.1.14 docs
> npx jsdoc2md ./src/index.js > docs.md

JSDOC_ERROR: There are no input files to process.
```

**Pull request closed without merging**
